module.exports = {
  preset: "jest-expo",
  setupFilesAfterEnv: ["<rootDir>/jest.setup.js"],
  moduleNameMapper: {
    "^@/(.*)$": "<rootDir>/$1",
  },
  collectCoverageFrom: [
    "<rootDir>/**/*.{js,jsx,ts,tsx}",
    "!<rootDir>/**/*.d.ts",
    "!<rootDir>/**/index.ts",
    "!<rootDir>/**/types.ts",
    "!<rootDir>/**/node_modules/**",
    "!<rootDir>/**/.expo/**",
    "!<rootDir>/app-example/**",
    "!<rootDir>/app/**",
    "!<rootDir>/coverage/**",
    "!<rootDir>/api/mock/**",
    "!<rootDir>/api/endpoints/**",
    "!<rootDir>/api/queries/**",
    "!<rootDir>/scripts/**",
    "!<rootDir>/tests/**",
    "!<rootDir>/babel.config.js",
    "!<rootDir>/metro.config.js",
    "!<rootDir>/jest.config.js",
    "!<rootDir>/tamagui.config.ts",
  ],
  coverageReporters: ["text-summary", "lcov", "json-summary"],
  coverageThreshold: {
    global: {
      lines: 50,
      statements: 50,
      functions: 50,
      branches: 50,
    },
  },
  testPathIgnorePatterns: ["/node_modules/", "/.expo/"],
};
